name: Titanic Project CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run unit tests
      run: |
        poetry run python -m unittest discover -s tests
    - name: Check formatting with isort
      run: |
        poetry run isort --check-only .
    - name: Check formatting with black
      run: |
        poetry run black --check .
    - name: Lint with ruff
      run: |
        poetry run ruff .
